//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoelSpadin.BraceCompleter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JoelSpadin.BraceCompleter.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} brace completion.
        /// </summary>
        public static string BraceCompletion {
            get {
                return ResourceManager.GetString("BraceCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically close braces in {0} files.
        /// </summary>
        public static string BraceCompletionToolTip {
            get {
                return ResourceManager.GetString("BraceCompletionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Languages.
        /// </summary>
        public static string ExtraLanguages {
            get {
                return ResourceManager.GetString("ExtraLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert closing brace immediately.
        /// </summary>
        public static string ImmediateCompletion {
            get {
                return ResourceManager.GetString("ImmediateCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserts the closing brace immediately after typing an opening brace.
        /// </summary>
        public static string ImmediateCompletionTip {
            get {
                return ResourceManager.GetString("ImmediateCompletionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent Braces.
        /// </summary>
        public static string IndentBraces {
            get {
                return ResourceManager.GetString("IndentBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent braces in C/C++ code files.  Set to the same value as &quot;Indent Braces, Formatting, C/C++, Text Editor&quot;.
        /// </summary>
        public static string IndentCppBracesToolTip {
            get {
                return ResourceManager.GetString("IndentCppBracesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Languages.
        /// </summary>
        public static string RegularLanguages {
            get {
                return ResourceManager.GetString("RegularLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all content types.
        /// </summary>
        public static string ShowAllTypes {
            get {
                return ResourceManager.GetString("ShowAllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all Visual Studio content types instead of filtering to code types.
        /// </summary>
        public static string ShowAllTypesToolTip {
            get {
                return ResourceManager.GetString("ShowAllTypesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Smart Formatting.
        /// </summary>
        public static string SmartFormat {
            get {
                return ResourceManager.GetString("SmartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Visual Studio&apos;s automatic formatting. Turning this on will override many of the other formatting settings..
        /// </summary>
        public static string SmartFormatTip {
            get {
                return ResourceManager.GetString("SmartFormatTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C/C++.
        /// </summary>
        public static string TypeCpp {
            get {
                return ResourceManager.GetString("TypeCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        public static string TypeCSharp {
            get {
                return ResourceManager.GetString("TypeCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS.
        /// </summary>
        public static string TypeCss {
            get {
                return ResourceManager.GetString("TypeCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript.
        /// </summary>
        public static string TypeJavaScript {
            get {
                return ResourceManager.GetString("TypeJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JScript.
        /// </summary>
        public static string TypeJScript {
            get {
                return ResourceManager.GetString("TypeJScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text.
        /// </summary>
        public static string TypePlainText {
            get {
                return ResourceManager.GetString("TypePlainText", resourceCulture);
            }
        }
    }
}
